{*
* @param Paginator $paginator
* @param array     $steps
*}

{if $paginator->pageCount > 1}
<div class="pagination pagination-centered">
	<ul>
		{if $paginator->isFirst()}
		<li class="disabled"><a href="#">&laquo;</a></li>
		{else}
		<li><a class="paginator-left" href="{link this, 'page' => $paginator->page - 1}">&laquo;</a></li>
		{/if}

		{foreach $steps as $step}
		<!--		{dump $step}-->
		{if $step == $paginator->page}
		<li class="active"><a href="{link this, 'page' => $step}">{$step}</a></li>
		{else}
		<li><a href="{link this, 'page' => $step}">{$step}</a></li>
		{/if}
				<!--{if $iterator->nextValue > $step + 1}<div><span>…</span></div>{/if}-->
		{/foreach}

		{if $paginator->isLast()}
		<li class="disabled"><a href="#">&raquo;</a></li>
		{else}
		<li><a href="{link this, 'page' => $paginator->page + 1}">&raquo;</a></li>
		{/if}
	</ul>
</div>
{/if}

