{block #usermenu}
<nav id="dropmenu">
	{foreach $children as $item}
	<li {if $item->isCurrent} class="active"{/if}>
		<a href="{$item->url}">
	<!--[if IE 7]><i class="icon-chevron-right"></i><span style="float: right;">{$item->label}</span><div class="clear"><![endif]-->
			<![if !IE 7]>{$item->label}<![endif]>
		</a>
		{if !$iterator->isLast()}
		<div class="delimiter"></div>
		{/if}
	</li>
	{/foreach}
</nav>
{/block}
