CREATE TABLE `send_emails` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`count` INT UNSIGNED NOT NULL,
	`type` TINYINT UNSIGNED NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
