/* přidání novinek */
CREATE TABLE `news` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`text` TEXT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `users_news` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`userID` INT UNSIGNED NULL,
	`newID` INT UNSIGNED NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `FKusers` FOREIGN KEY (`userID`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK__news` FOREIGN KEY (`newID`) REFERENCES `news` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

ALTER TABLE `news`
	ADD COLUMN `name` VARCHAR(50) NOT NULL AFTER `id`;

ALTER TABLE `news`
	ADD COLUMN `release` TINYINT(1) UNSIGNED NULL DEFAULT '0' AFTER `text`,
	ADD COLUMN `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `release`;