ALTER TABLE `users`
	DROP COLUMN `fbuid`;
	
	ALTER TABLE `users`
	DROP COLUMN `id_couple`,
	DROP COLUMN `user_property`,
	DROP COLUMN `interested_in`,
	DROP COLUMN `first_sentence`,
	DROP COLUMN `about_me`,
	DROP COLUMN `marital_state`,
	DROP COLUMN `orientation`,
	DROP COLUMN `tallness`,
	DROP COLUMN `shape`,
	DROP COLUMN `penis_length`,
	DROP COLUMN `penis_width`,
	DROP COLUMN `smoke`,
	DROP COLUMN `drink`,
	DROP COLUMN `graduation`,
	DROP COLUMN `bra_size`,
	DROP COLUMN `hair_colour`,
	DROP COLUMN `threesome`,
	DROP COLUMN `anal`,
	DROP COLUMN `group`,
	DROP COLUMN `bdsm`,
	DROP COLUMN `swallow`,
	DROP COLUMN `cum`,
	DROP COLUMN `oral`,
	DROP COLUMN `piss`,
	DROP COLUMN `sex_massage`,
	DROP COLUMN `petting`,
	DROP COLUMN `fisting`,
	DROP COLUMN `deepthrought`,
	DROP COLUMN `want_to_meet_men`,
	DROP COLUMN `want_to_meet_women`,
	DROP COLUMN `want_to_meet_couple`,
	DROP COLUMN `want_to_meet_couple_men`,
	DROP COLUMN `want_to_meet_couple_women`,
	DROP COLUMN `want_to_meet_group`;
	
	
	-- Dumping structure for table priznaniosexu.users
CREATE TABLE IF NOT EXISTS `users_properties` (
  `id` int(11) unsigned NOT NULL,
  `id_couple` int(11) DEFAULT NULL,
  `user_property` varchar(11) DEFAULT '',
  `interested_in` varchar(11) DEFAULT '',
  `first_sentence` varchar(200) DEFAULT '',
  `about_me` varchar(300) DEFAULT '',
  `marital_state` varchar(50) DEFAULT '',
  `orientation` varchar(50) DEFAULT '',
  `tallness` int(11) DEFAULT NULL,
  `shape` varchar(50) DEFAULT '',
  `penis_length` varchar(50) DEFAULT NULL,
  `penis_width` varchar(50) DEFAULT NULL,
  `smoke` varchar(50) DEFAULT '',
  `drink` varchar(50) DEFAULT '',
  `graduation` varchar(50) DEFAULT NULL,
  `bra_size` varchar(11) DEFAULT NULL,
  `hair_colour` varchar(50) DEFAULT '',
  `threesome` tinyint(1) DEFAULT NULL,
  `anal` tinyint(1) DEFAULT NULL,
  `group` tinyint(1) DEFAULT NULL,
  `bdsm` tinyint(1) DEFAULT NULL,
  `swallow` tinyint(1) DEFAULT NULL,
  `cum` tinyint(1) DEFAULT NULL,
  `oral` tinyint(1) DEFAULT NULL,
  `piss` tinyint(1) DEFAULT NULL,
  `sex_massage` tinyint(1) DEFAULT NULL,
  `petting` tinyint(1) DEFAULT NULL,
  `fisting` tinyint(1) DEFAULT NULL,
  `deepthrought` tinyint(1) DEFAULT NULL,
  `want_to_meet_men` tinyint(1) DEFAULT NULL,
  `want_to_meet_women` tinyint(1) DEFAULT NULL,
  `want_to_meet_couple` tinyint(1) DEFAULT NULL,
  `want_to_meet_couple_men` tinyint(1) DEFAULT NULL,
  `want_to_meet_couple_women` tinyint(1) DEFAULT NULL,
  `want_to_meet_group` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

	