{contentType application/xml; charset=utf-8}
<<?php ?>?xml version="1.0" ?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
	<channel>
		{block #properties}
		{foreach $channelProperties as $key => $property}
			<{$key}>{if is_array($property)}{include #properties 'channelProperties' => $property}{else}{$property}{/if}</{$key}>
		{/foreach}
		{/block}
		{ifset $link}
		<atom:link href="{$link}" rel="self" type="application/rss+xml" />
		{/ifset}

		{foreach $items as $item}
		<item>
			{foreach $item as $key => $property}
			<{$key}>{$property}</{$key}>
			{/foreach}
		</item>
		{/foreach}
	</channel>
</rss>